#cloud-config

autoinstall:
  version: 1

  source: 
    id: ubuntu-desktop-minimal

  interactive-sections:
    - storage

  packages:
    - ubuntu-desktop
    - ibus-mozc
    - mozc-data
    - mozc-utils-gui
    - build-essential
    - git
    - gh
    - tmux
    - curl

  snaps:
    # - name: firefox
    #   channel: esr/stable
    - name: snap-store
    - name: snapd-desktop-integration
    - name: gtk-common-themes
    - name: nvim
      classic: true


  codecs:
    install: true

  timezone: "Asia/Tokyo"

  ssh:
    install-server: true
    allow-pw: true

  late-commands:
    - curtin in-target -- snap remove firefox
    - curtin in-target -- snap install firefox --channel=esr/stable
  user-data:
    users: ['']
    hostname: ubuntu-ai
